첫번째 pr
f-lab-edu/LaundryDo pull request #36
Opened 2023-07-31 10:41 UTC by watanka

**작성한 부분**
- ci/cd
- docker-compose
- 도메인 로직 작성
- sqlalchemy와 도메인 모델 결합
- sqlalchemy relationship을 인식하는 FakeRepository 생성

**아직 작성하지 않은 부분**
- docker-compose에서 FastAPI와 DB 서버 간의 연결. (DB, FastAPI 각각은 작동함)
- 프로세스별 각 clothes, order, laundrybag, machine의 state 변화 (scheduler를 어느 시점들에 넣어야할지 정의해야 state들도 명확해질듯함)
- apscheduler

2023-08-03 13:33 UTC, f-lab-jorge reviewed
코멘트 드렸습니다!
패턴이 잘 적용되어서 코드가 깔끔하군요

2023-08-03 13:33 UTC, f-lab-jorge commented on src/application/services.py
> +        READY_laundrybags = uow.laundrybags.get_by_status(status=LaundryBagState.READY)
READY_laundrybags 이라는 변수명이 어색해보여요. 파이썬에서 주로 사용하는 camel_case 로 맞추면 될거 같아요

2023-08-03 13:33 UTC, f-lab-jorge commented on src/application/services.py
> +        available_machines = deque(uow.machines.get_by_status(status = MachineState.READY))
status를  MachineState.READY 같은 상수로 두는거 아주 좋습니다

2023-08-03 13:33 UTC, f-lab-jorge commented on src/domain/machine.py
> +        return hash(self.machineid) == hash(other.machineid)
hash가 필요한가요?

2023-08-03 13:33 UTC, f-lab-jorge commented on src/infrastructure/fastapi/app.py
> +    scheduler.add_job(print_hi, 'cron', second='*/5')
테스트로 들어간거 같은데 다음 코드에선 뺴면 될거 같아요

2023-08-03 13:33 UTC, f-lab-jorge commented on src/domain/machine.py
> +    def start(self, laundrybag: LaundryBag, exec_time):
이 함수에서 exec_time이 now() 가 아닐때가 있나요? 없다면 굳이 없어도 되는 인자로 보이네요

2023-08-04 04:01 UTC, watanka commented on src/domain/machine.py
> +    def start(self, laundrybag: LaundryBag, exec_time):
exec_time은 테스트할 때, 시간에 따라서 바뀌는 세탁기 상태를 조정하려고 따로 빼놓았습니다.

시간이 들어가지 않더라도, 세탁기 상태를 직접 바꿔서 테스트할 수도 있을 것 같긴합니다.

빼는 게 더 나을까요?

2023-08-04 04:03 UTC, watanka commented on src/application/services.py
> +    '''PUT LAUNDRYBAG INTO AVAILABLE MACHINE
꽉 차거나 일정 시간이 지난 빨래바구니를 세탁기에 집어넣는 코드입니다. apscheduler로 처리하려고 합니다.

2023-08-04 04:03 UTC, watanka commented on src/application/services.py
> +        READY_laundrybags = uow.laundrybags.get_by_status(status=LaundryBagState.READY)
넵 laundrybags_in_ready로 바꾸었습니다!

2023-08-04 04:10 UTC, watanka commented on src/domain/machine.py
> +        return hash(self.machineid) == hash(other.machineid)
machine은 고유한 id를 가진 엔티티이니, hash가 필요하지 않겠네요! 짚어주셔서 감사합니다.

2023-08-11 13:06 UTC, f-lab-jorge requested changes
코멘트 추가로 드렸습니다

2023-08-11 13:06 UTC, f-lab-jorge commented on src/domain/machine.py
> +        return hash(self.machineid) == hash(other.machineid)
넵 이부분 수정하면 될거 같아요

2023-08-11 13:06 UTC, f-lab-jorge commented on src/domain/machine.py
> +    def start(self, laundrybag: LaundryBag, exec_time):
음 다시보니 테스트를 위해서 인자를 넣을 필요는 없어보이네요.
테스트시에는 직접 상태를 설정하면 될 거 같아요

2023-08-25 06:28 UTC, watanka commented on src/domain/machine.py
> +    def start(self, laundrybag: LaundryBag, exec_time):
machine 테스트 시에 남은 시간(`remainingTime` 함수)이나 런타임(`get_runtime` 함수)을 테스트하는 부분이 있습니다. exec_time 인자를 없앤다면, mock을 사용해야할까요? mock을 사용하려고 하니, 다음과 같은 에러가 발생해서 질문드립니다. `TypeError: cannot set 'now' attribute of immutable type 'datetime.datetime'`

2023-09-05 11:37 UTC, watanka commented on src/domain/machine.py
> +    def start(self, laundrybag: LaundryBag, exec_time):
exec_time 인자 제외했습니다. `freezegun`이라는 라이브러리 사용해서 시간 조정했습니다.

2023-09-06 01:15 UTC, watanka commented on src/domain/machine.py
> +        return hash(self.machineid) == hash(other.machineid)
제가 잘못 이해한 것 같습니다. machine은 고유한 Id를 가진 엔티티이고, 그와 별개로 sorted 함수 사용을 위해서는 __hash__가 필요할 것 같습니다. (빨래바구니를 할당하기 위한 Machine List를 불러올 때, sorted함수를 사용해서 가능한 머신 중 가장 오래 휴식을 취한 머신을 불러옵니다)
파이썬 코드에서 불러오는 방법 외에 데이터베이스에서 불러올 때 sort해서 하는 방법도 있을 것 같습니다.

2023-09-12 11:49 UTC, merged